### ISSUE TITLE
Who is there?

### ISSUE THREAD

**Issue by urskalbitzer** [livingingroups/livingingroups.github.io#2]
Just curious who owns this account. Are you a member for the EAS department?

**Comment by chasenunez** [comment]
hello, this is chase, finally finding your opened issue, and now resolving it. Bon Voyage!

**Comment by urskalbitzer** [comment]
I am glad you were able to solve this issue. But why Baboon automation?

**Comment by chasenunez** [comment]
ah yes, i assigned it to myself to resolve through my baboon workflow
